kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boskos
rules:
  - apiGroups: ["boskos.k8s.io"]
    verbs: ["*"]
    resources: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boskos
subjects:
  - kind: ServiceAccount
    name: boskos
    namespace: test-pods
roleRef:
  kind: ClusterRole
  name: boskos
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos
  namespace: test-pods
spec:
  replicas: 1 # one canonical source of resources
  selector:
    matchLabels:
      app: boskos
  template:
    metadata:
      labels:
        app: boskos
      namespace: test-pods
    spec:
      serviceAccountName: boskos
      terminationGracePeriodSeconds: 30
      containers:
        - name: boskos
          image: gcr.io/k8s-staging-boskos/boskos:v20260107-c2c6f43
          args:
            - --config=/etc/config/config
            - --namespace=test-pods
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: boskos-config
              mountPath: /etc/config
              readOnly: true
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
      tolerations:
        - key: node-group
          operator: Equal
          value: stable
          effect: NoSchedule
      nodeSelector:
        node-group: stable
      volumes:
        - name: boskos-config
          configMap:
            name: resources
---
apiVersion: v1
kind: Service
metadata:
  name: boskos
  namespace: test-pods
  labels:
    app: boskos
spec:
  selector:
    app: boskos
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boskos-metrics
  namespace: test-pods
  labels:
    app: boskos-metrics
spec:
  selector:
    app: boskos
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: boskos
  namespace: test-pods
