apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-pods

resources:
  - boskos-janitor.yaml
  - boskos-reaper.yaml
  - configmap.yaml
  - boskos.yaml
  - build-serviceaccounts.yaml
  - externalsecrets.yaml
  - limit-range.yaml
  - poddisruptionbudget.yaml
