apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure
  annotations:
    azure.workload.identity/client-id: 333bb18b-207b-4abd-9ed0-e7e3834378b1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rg-cleanup
  annotations:
    azure.workload.identity/client-id: f23f8fcc-855b-40fd-a41b-b329ccdb95a1
