apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sippy
  namespace: sippy
  labels:
    app: sippy
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "sippy-ingress-prod"
    networking.gke.io/managed-certificates: sippy-k8s-io
spec:
  defaultBackend:
    service:
      name: sippy
      port:
        number: 9080