apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sippy
  namespace: sippy
  labels:
    app: sippy
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "sippy-ingress-prod"
    networking.gke.io/managed-certificates: sippy-k8s-io
spec:
  backend:
    serviceName: sippy
    servicePort: 8080
