files:
- name: linux/amd64/ecr-credential-provider-linux-amd64
  sha256: 758ba8d4808d4d8f1345aebfa3dfc1a072fe0b0b8187480fb7047a1110baa69a
- name: linux/amd64/ecr-credential-provider-linux-amd64.sha256
  sha256: 09d2c2f59ab7d385f6db4a5bbcec63d97d82d7a215afcd6c48493841aff38390
- name: linux/arm64/ecr-credential-provider-linux-arm64
  sha256: 880dc2b278c08bf569370b0131520c0dc8561dbbb31c56d5d528c8a5655aa802
- name: linux/arm64/ecr-credential-provider-linux-arm64.sha256
  sha256: 557d31f8f28a035b22b3f00b73ea47e8586637b330656d9a7c09bba8c6cf933f
- name: windows/amd64/ecr-credential-provider-windows-amd64
  sha256: c324ab2ed3c6b45659ee2586b7d9e4808c327d270baa3a25a2b3277a59b70dc9
- name: windows/amd64/ecr-credential-provider-windows-amd64.sha256
  sha256: a82aebed964d32ee37d0554677f95b4b44476fe5a28eebe7fac3bb3c170be4c6
