apiVersion: v1
kind: Service
metadata:
  name: codesearch
  namespace: codesearch
  labels:
    app: codesearch
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: codesearch
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
