---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-infra-cherrypick-robot-github-token
spec:
  data:
    - remoteRef:
        key: k8s-infra-cherrypick-robot-github-token
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-public
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-eks-prow-build-cluster
spec:
  data:
    - remoteRef:
        key: eks-prow-build-cluster-kubeconfig
      secretKey: kubeconfig
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-k8s-infra-aks-prow-build
spec:
  data:
    - remoteRef:
        key: k8s-infra-aks-prow-build-kubeconfig
      secretKey: kubeconfig
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-k8s-infra-kops-prow-build
spec:
  data:
    - remoteRef:
        key: k8s-infra-kops-prow-build-kubeconfig
      secretKey: kubeconfig
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-k8s-infra-prow-build
spec:
  data:
    - remoteRef:
        key: k8s-infra-prow-build-kubeconfig
      secretKey: kubeconfig
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-k8s-infra-prow-build-trusted
spec:
  data:
    - remoteRef:
        key: k8s-infra-prow-build-trusted-kubeconfig
      secretKey: kubeconfig
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-k8s-infra-prow
spec:
  data:
    - remoteRef:
        key: k8s-infra-prow-kubeconfig
      secretKey: kubeconfig
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-token
spec:
  data:
    - remoteRef:
        key: oauth-token
      secretKey: oauth
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-token
spec:
  data:
    - remoteRef:
        key: slack-token
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hmac-token
spec:
  data:
    - remoteRef:
        key: hmac-token
      secretKey: hmac
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth-config
spec:
  data:
    - remoteRef:
        key: github-oauth-config
      secretKey: secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cat-api-key
spec:
  data:
    - remoteRef:
        key: cat-api-key
      secretKey: api-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unsplash-api-key
spec:
  data:
    - remoteRef:
        key: unsplash-api-key
      secretKey: honk.txt
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cookie
spec:
  data:
    - remoteRef:
        key: cookie
      secretKey: secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
