files:
- name: 1.34.1/darwin/amd64/kops
  sha256: 0c34a0809ea7c29322c25840a1c4a2abecd4f0bab1a8b975b1fb9fd3df236c86
- name: 1.34.1/darwin/amd64/kops.sha256
  sha256: f1a26d136c044ec167994031f8f3fd8e7b24fc179e0796bc95d7fe650bc280c9
- name: 1.34.1/darwin/arm64/kops
  sha256: eb03aa42c5b8fc73ba12a31ed925f679507e8c5922d29b4f0c3f26a1718f0180
- name: 1.34.1/darwin/arm64/kops.sha256
  sha256: 0b18098bee81c859508d803e19cf7513e4fbdbc4e97016316b91185e24c91ca4
- name: 1.34.1/images/dns-controller-amd64.tar.gz
  sha256: d4b8b0042dcc3434387fa85357f44cd9e2b6f85a3c5c74ba8f3a724dc92b800b
- name: 1.34.1/images/dns-controller-amd64.tar.gz.sha256
  sha256: d3f297ecf33590ff86d02c95f0d85be4be872e39396cc16a2030fc9e651e6c86
- name: 1.34.1/images/dns-controller-arm64.tar.gz
  sha256: 7d49bea335dc109ebfa875c849f94bb4b7320f8324a13f701012789c2e318389
- name: 1.34.1/images/dns-controller-arm64.tar.gz.sha256
  sha256: a88748d821a84889101d837dd719cd31b4d8b2d3c6d0c3b30925637ebc48c523
- name: 1.34.1/images/kops-controller-amd64.tar.gz
  sha256: b49e495a20bdbf7dac6bd33d66251371d72cebab8ec985052d33b70991a13dbe
- name: 1.34.1/images/kops-controller-amd64.tar.gz.sha256
  sha256: ac60182a1cbd7659d4498aaa98b968a2c11a5b30f7adc593e24fa88e80f82d98
- name: 1.34.1/images/kops-controller-arm64.tar.gz
  sha256: b9db69e8ad2f40d09c0fa8d170e4c8bd0942c621da6fd9f0a7d0d674db69f4b8
- name: 1.34.1/images/kops-controller-arm64.tar.gz.sha256
  sha256: 3723ddb1e12f211ffbb2b2efdc38f49605537ea99fe3702b548f7911cda21d14
- name: 1.34.1/images/kops-utils-cp-amd64.tar.gz
  sha256: a9110813734dd202e343f3b09e5606ff3f90f36a8295754c0624ab6c99bc3c61
- name: 1.34.1/images/kops-utils-cp-amd64.tar.gz.sha256
  sha256: ebfbab98f74bf2c8cad89fde257af05ff9f91741c8761e48e5bf5f85b5077212
- name: 1.34.1/images/kops-utils-cp-arm64.tar.gz
  sha256: 0cbc9771dcbad3055ef2645a6405794883ecabd38d1a0bf0e12321f752583f28
- name: 1.34.1/images/kops-utils-cp-arm64.tar.gz.sha256
  sha256: 2a7de686d395d5fcbe5b7cbb1cdbc51d9bc6d55e952cb41215a5c7e6bf388454
- name: 1.34.1/images/kube-apiserver-healthcheck-amd64.tar.gz
  sha256: 39c15510b166c52315ce05143cf0510fc2dd4035f18cd7fb2630c1b34db6edd2
- name: 1.34.1/images/kube-apiserver-healthcheck-amd64.tar.gz.sha256
  sha256: 9c81a878bc19dbd6d34a51b509559e4f2074b590300294e4c32c1ee53992800d
- name: 1.34.1/images/kube-apiserver-healthcheck-arm64.tar.gz
  sha256: 8ddef0d9275b6b18115c569b330cdb70186f1788d7c6f53555ed43dfff72de04
- name: 1.34.1/images/kube-apiserver-healthcheck-arm64.tar.gz.sha256
  sha256: a1b27dcbc67d892520b51488aa8bb48195f1d054db12855b9be7b593bac56b5d
- name: 1.34.1/linux/amd64/channels
  sha256: ca69ef7df6ab6fba087ef0fd8e9555e746497fbab99d615de13d253436d8565f
- name: 1.34.1/linux/amd64/channels.sha256
  sha256: 263e95c57249f2caef4198be56523437411145c1b92e8854b73d1023c13477cd
- name: 1.34.1/linux/amd64/kops
  sha256: 596140c31bb1499e7633e5de6789ce0324571c204ee80b1da7168744daf0d30e
- name: 1.34.1/linux/amd64/kops.sha256
  sha256: c31c23643beb27e29036c02b484d704d70732811b85cc8a734ef98ebc9275f31
- name: 1.34.1/linux/amd64/nodeup
  sha256: 614bdf819824743e81880cdcb91200cb3e22f9d0c3fe5c8b2ac0e22724d737fc
- name: 1.34.1/linux/amd64/nodeup.sha256
  sha256: add9819c8708c5419ac08334d265fe5b9138082d5731ec584fdce6ac58d58b7d
- name: 1.34.1/linux/amd64/protokube
  sha256: a122c78c8a2d8630684a6b53fa3dd262f971b36e433a0edcab03159101253e70
- name: 1.34.1/linux/amd64/protokube.sha256
  sha256: 496084e88c44b047566cd631eb3dda38f5c1855702660c5241c27593e8e264b0
- name: 1.34.1/linux/arm64/channels
  sha256: 839d297830d0e7f9e594463fdf3ac23d014065fb70fddd6a126f76409a94a36d
- name: 1.34.1/linux/arm64/channels.sha256
  sha256: c53a1ca8291f4e39eee16713d5a346ff4594ee94b85ed808eb60af3d05b1a6ef
- name: 1.34.1/linux/arm64/kops
  sha256: 5ddb308b161ad1ef94686888ec04d114557f258e6a923484b74be141cecd8ed1
- name: 1.34.1/linux/arm64/kops.sha256
  sha256: c7e8933527b41cf193f794ad8535c3a76955fbd628ed31d52d6bdef3f8b8a66d
- name: 1.34.1/linux/arm64/nodeup
  sha256: 7f1f8ae16718feee6c30e6621a39dfbd90d5bac44ca9e038c7d448b7f1e7405b
- name: 1.34.1/linux/arm64/nodeup.sha256
  sha256: c0950cc9eec5ccb7aae0bc140c7bcb49dae97d03e10cf85db62cde99cb0e4228
- name: 1.34.1/linux/arm64/protokube
  sha256: fc5f1667b2c0020d244c84ed81bd8dd1545012edc1bc8e0fc8fcc2c6b4fc3323
- name: 1.34.1/linux/arm64/protokube.sha256
  sha256: 0a0c7a5e8dece2f761d5e77568f175558b8bdec76c908b8a2f01c63dd8d76ebf
- name: 1.34.1/windows/amd64/kops.exe
  sha256: 75513058f301903dca937252a64d7efa01686de9bc8ec0ac4efcfca2f245241e
- name: 1.34.1/windows/amd64/kops.exe.sha256
  sha256: ba01181c5e8936108e35e3b5c98d637a047227320b681a5256f8508031044413
