files:
- name: 1.35.0-alpha.1/darwin/amd64/kops
  sha256: 9ba869c67222645a53e0698bca745d5a21482de712f2a30bcd603e76e0fd7119
- name: 1.35.0-alpha.1/darwin/amd64/kops.sha256
  sha256: a37c4c120ac3e9f3e6a87807e95b87b9c3cba234fe14576c5c8b3e06ec164c9f
- name: 1.35.0-alpha.1/darwin/arm64/kops
  sha256: b7555efb4920f71c59cc7f524ddfdb402037bd73087ff10bf7e63f9bde0f000b
- name: 1.35.0-alpha.1/darwin/arm64/kops.sha256
  sha256: 274aaab807f05eab9ad211e6e95d5738fa01333941883d396f3eea1bf3d7e1f1
- name: 1.35.0-alpha.1/images/dns-controller-amd64.tar.gz
  sha256: b04d3305431781b35dee9eaf22449e75baa21a000f80a8238e391faed1fd1296
- name: 1.35.0-alpha.1/images/dns-controller-amd64.tar.gz.sha256
  sha256: c2c38f55838a3c59b163a1697c47ae5ef8f19b24260cea70711084e6700e7a0a
- name: 1.35.0-alpha.1/images/dns-controller-arm64.tar.gz
  sha256: bc475119bb4548e50af9cf640136cacdc8d77f6a3b2634d9bd5186cfeb4ed268
- name: 1.35.0-alpha.1/images/dns-controller-arm64.tar.gz.sha256
  sha256: a90f7d31d32ecf0042a83b53b0352930f1c205444dfc7af299708b1d8f9d5649
- name: 1.35.0-alpha.1/images/kops-controller-amd64.tar.gz
  sha256: 72b0f1c5f37528629bf8538cb2224ca6f09fb999e0ee1fee69f7af730a5a07e6
- name: 1.35.0-alpha.1/images/kops-controller-amd64.tar.gz.sha256
  sha256: 1bfa74a00bc2e363b9e6d5305b574d99246b5172343ac1489c1edc43664a7de3
- name: 1.35.0-alpha.1/images/kops-controller-arm64.tar.gz
  sha256: 536ca0bde29b5242bed6fc641f6ca5b54c08ce318fe36ba5869be44326dc6d33
- name: 1.35.0-alpha.1/images/kops-controller-arm64.tar.gz.sha256
  sha256: 9db88e7b8dfbe10d3557e756ffd20a446dfeb098d803c75a9d9c830ec10b6e7b
- name: 1.35.0-alpha.1/images/kops-utils-cp-amd64.tar.gz
  sha256: 7ed0c9ccc9c6755dd702b9b40a0813fe2c6022737a33fa957f8ad1be0252639c
- name: 1.35.0-alpha.1/images/kops-utils-cp-amd64.tar.gz.sha256
  sha256: f3a0563e0bd214938c417a8b7e64ae55c207c01de43c247dc33664d85ff49658
- name: 1.35.0-alpha.1/images/kops-utils-cp-arm64.tar.gz
  sha256: 555599a51f1dd2467003017f763b3c4c1e3f31899ec61b82ddb20e2f282c3fef
- name: 1.35.0-alpha.1/images/kops-utils-cp-arm64.tar.gz.sha256
  sha256: d99ebdf67b2056c19e1777ab97d3697265806d4e13601f439a69a7eed366dc69
- name: 1.35.0-alpha.1/images/kube-apiserver-healthcheck-amd64.tar.gz
  sha256: 024ea74ad3f1d6e6c756093bbb2fb09430b20ceeec336e2c0e4b5d1605de6209
- name: 1.35.0-alpha.1/images/kube-apiserver-healthcheck-amd64.tar.gz.sha256
  sha256: b845d99e4bf853b21eaf777b75bff6e573a74e8aa25a378671af473d83e2b7ec
- name: 1.35.0-alpha.1/images/kube-apiserver-healthcheck-arm64.tar.gz
  sha256: 813bd78b054de3a3fff17439fe914b414ca3e57f803ec3ed099de6790ff707fe
- name: 1.35.0-alpha.1/images/kube-apiserver-healthcheck-arm64.tar.gz.sha256
  sha256: df0293e2fb14eea56048a1d074ddcf93041b92e9ba95bedda0a19ccb99d7699e
- name: 1.35.0-alpha.1/linux/amd64/channels
  sha256: d95c45f35275e49c53d7faec668ff45e4f968dd86f59a1b1f7bbf49678c5b233
- name: 1.35.0-alpha.1/linux/amd64/channels.sha256
  sha256: 03ca083178d987ee29cc18ed943fb64c6442601c528e0e9eec4f7776e5c0b557
- name: 1.35.0-alpha.1/linux/amd64/kops
  sha256: abc421ebf4c5013bda2a057fb9f48c6cb7d374715ee3c128f008bd14d705f88d
- name: 1.35.0-alpha.1/linux/amd64/kops.sha256
  sha256: b41e4abc619aed77cca232c28b77a470feab4b3b68361ccdb887f589d57d56a5
- name: 1.35.0-alpha.1/linux/amd64/nodeup
  sha256: e2c34d20c273311bc658603427c3ed86a3a8e8e7464f0204d99ba5d676044399
- name: 1.35.0-alpha.1/linux/amd64/nodeup.sha256
  sha256: ce10576093e61d8ed971ef0ac35d29711fa598a3f98d843362b4af5d9ab0e88e
- name: 1.35.0-alpha.1/linux/amd64/protokube
  sha256: 6021dcd2fbb895172bc0cfe243b1ec57f650e5780deecfff66683de8b8b19362
- name: 1.35.0-alpha.1/linux/amd64/protokube.sha256
  sha256: 7075a908e29a456d17c281be3cfdb3e92d3c53949df609432debc43c560c59d6
- name: 1.35.0-alpha.1/linux/arm64/channels
  sha256: 1514e8a34bbc32c4934891f292a24f078a351cbc12e287ba884f9aa0b85f58c3
- name: 1.35.0-alpha.1/linux/arm64/channels.sha256
  sha256: 4ffd162d42278b370a6ed4d0427be4464f8aa5e122e8a27ff766b2f7e6182604
- name: 1.35.0-alpha.1/linux/arm64/kops
  sha256: 40b7c33631793d6e419e78f7003cef50a0fb3e940c81f9c287225c34bee76ed4
- name: 1.35.0-alpha.1/linux/arm64/kops.sha256
  sha256: 67f467408305d2b6ecfd57e3848d99a6e7815f4fc441e7251a3969f2e9a663d0
- name: 1.35.0-alpha.1/linux/arm64/nodeup
  sha256: 55f07d23805bded100f3ef0ecd2ea7397f21405ead8675c47d76d58f2af9cb5f
- name: 1.35.0-alpha.1/linux/arm64/nodeup.sha256
  sha256: be09326088aa842c09af0f7e22532505be8df39ce5d46ac2cc5c35e049d2527e
- name: 1.35.0-alpha.1/linux/arm64/protokube
  sha256: 8d604d9f9d97dc76ad229b45409276aacacd20e7f49c6daa4121382aa3eb425f
- name: 1.35.0-alpha.1/linux/arm64/protokube.sha256
  sha256: 20b570b2b6450c451269fb1ce7442a607494140a2b9c067e19073b11f6974b43
- name: 1.35.0-alpha.1/windows/amd64/kops.exe
  sha256: 56a65b32b577919ca5b58b73319298165cbeaa41251e22c717b41555a61d65d6
- name: 1.35.0-alpha.1/windows/amd64/kops.exe.sha256
  sha256: c3aee141a0630c97a2d6ff7f7d408a664d8426e0ce5577a3eae6c0da6eee1ddf
