files:
- name: 1.35.0-beta.1/darwin/amd64/kops
  sha256: 4c041c27f02f3b28da78c2e469fa8de964579679d116d6def7f511ec6825c1af
- name: 1.35.0-beta.1/darwin/amd64/kops.sha256
  sha256: 0db6609682d1557b11da6ff8f2ee06d7a2f2b1ccef1e2700f903381519a1f524
- name: 1.35.0-beta.1/darwin/arm64/kops
  sha256: 1113f2cf3a0a82e160ebe4b7a761a0cd3f065f7ea891c6a3c26d4b028aaa80c6
- name: 1.35.0-beta.1/darwin/arm64/kops.sha256
  sha256: 0b17344e228128eaa7a459c60429a7b2c83c4016eb2caac7d18148458f446bd3
- name: 1.35.0-beta.1/images/discovery-server-amd64.tar.gz
  sha256: 441997b008ab2319100e871d9e9beb8cb31ba27e02061155b900b05379347b71
- name: 1.35.0-beta.1/images/discovery-server-amd64.tar.gz.sha256
  sha256: 84120d44370d4799891ac1cf23622fbf980bf3a80776c6fa5ca26b7f1726e606
- name: 1.35.0-beta.1/images/discovery-server-arm64.tar.gz
  sha256: 98a952f95fd333f09c1c319f49f46706c5f11b8d65f71da17eac4905ef4e81cb
- name: 1.35.0-beta.1/images/discovery-server-arm64.tar.gz.sha256
  sha256: 2c885c20ecc768aa67765cb3bbfb8c918c8651eeb2c495d8a5900bfd45d8282c
- name: 1.35.0-beta.1/images/dns-controller-amd64.tar.gz
  sha256: 8a41b1cb35a57f8a74b85dd25f7546729456be4d583f0fee5718358b51ed6ac5
- name: 1.35.0-beta.1/images/dns-controller-amd64.tar.gz.sha256
  sha256: 344679c786ca53584c6f302496c688c9a4030102b7f3732ef508c396f6958877
- name: 1.35.0-beta.1/images/dns-controller-arm64.tar.gz
  sha256: 2587498c781b62df5e2cff1d1ffc293954bb57c4599befd0001719e59d6f5cde
- name: 1.35.0-beta.1/images/dns-controller-arm64.tar.gz.sha256
  sha256: a41e9cce4257a466ce28184d47b07cf9bd74708f34d9545f35c70c8702437379
- name: 1.35.0-beta.1/images/kops-controller-amd64.tar.gz
  sha256: a9d9261ec45b255fe58518a3ba41903a05cd165e340ccd0d4df20445e41d4ca4
- name: 1.35.0-beta.1/images/kops-controller-amd64.tar.gz.sha256
  sha256: cf2bfd3fbc7acd0d3b635ee56e42b561528e05391a55bccdf8cf6d19bac4891b
- name: 1.35.0-beta.1/images/kops-controller-arm64.tar.gz
  sha256: a6a65429ac9eec0fbd6986005cf82f1c320daadf678fde248cca976d87a08fac
- name: 1.35.0-beta.1/images/kops-controller-arm64.tar.gz.sha256
  sha256: 141eb02f92277b1af68c11cb9de6dded6b9697acb5a7e6761e89e19fd9eda5d3
- name: 1.35.0-beta.1/images/kops-utils-cp-amd64.tar.gz
  sha256: 7e7cf4b5f4a37ba7c33250b9f048acb02d6bface1c66372e82259d6b83e70203
- name: 1.35.0-beta.1/images/kops-utils-cp-amd64.tar.gz.sha256
  sha256: b7ceeae50d6f696811049670e45c9c246507c2a601f904f7a9efe556b08e7f5c
- name: 1.35.0-beta.1/images/kops-utils-cp-arm64.tar.gz
  sha256: 219606ee84532d28d7b16bc603e65888e62c66a990f7ebd9caaf05713ed64f63
- name: 1.35.0-beta.1/images/kops-utils-cp-arm64.tar.gz.sha256
  sha256: 1ecaed27d16df2a9699a1fb3c6e2e2b0da98ce321ad27657b100607297aa06c6
- name: 1.35.0-beta.1/images/kube-apiserver-healthcheck-amd64.tar.gz
  sha256: 3951b38e4b59893c9524b0cc53bd68f7b7e04f5c8c9688c673ae996b89ab599f
- name: 1.35.0-beta.1/images/kube-apiserver-healthcheck-amd64.tar.gz.sha256
  sha256: 200e07c9a477a2590a946db2681d49ba5ce37e6d5b28c6ad7f19f4119d424504
- name: 1.35.0-beta.1/images/kube-apiserver-healthcheck-arm64.tar.gz
  sha256: ce04c734c2bb23690f7844ada2d0881127b3dcb4f452b00569d6dc33ad84fc1b
- name: 1.35.0-beta.1/images/kube-apiserver-healthcheck-arm64.tar.gz.sha256
  sha256: 430900133d712dcaa676fbfa647a28d5de5ef07b4d3827eb970b964a576c6c7d
- name: 1.35.0-beta.1/linux/amd64/channels
  sha256: ee56aae744d251bbad2ec3bfe49c70cf172749acb3474d8beee7e41f368e4512
- name: 1.35.0-beta.1/linux/amd64/channels.sha256
  sha256: 8f9190d077a468435fba79932ac2e5b0bc2b680c555c53b8ab390046e168405e
- name: 1.35.0-beta.1/linux/amd64/kops
  sha256: fa22dc2315c0fd685cdc819b6027fd1edbca9cb611336a7e205b78a7d951442e
- name: 1.35.0-beta.1/linux/amd64/kops.sha256
  sha256: d34e0c8fd243a71250c08355a14f3f13b6ae530c968261aa2f81e28b44dae47c
- name: 1.35.0-beta.1/linux/amd64/nodeup
  sha256: 9917fc05554b5fae4e54839c30931a2e2d0106aabd7b1277c0d3398970a5f942
- name: 1.35.0-beta.1/linux/amd64/nodeup.sha256
  sha256: afa26e162010671d8cd9354e50df4f676988dc47a6ac935937f086137625c70c
- name: 1.35.0-beta.1/linux/amd64/protokube
  sha256: 4e13767267fee022540178f414472a1bcc7fd499a2274174defd19ff434d4c88
- name: 1.35.0-beta.1/linux/amd64/protokube.sha256
  sha256: 1a4a1d79901886c41edff721a2114b69efa1df6a5cfb83ba396594979f6bb524
- name: 1.35.0-beta.1/linux/arm64/channels
  sha256: 8e356e9df5960e5ad5c437b1088ecec76f765d7884ff6eb3a462b921e644cd86
- name: 1.35.0-beta.1/linux/arm64/channels.sha256
  sha256: 3c2bc753ffbc321bc4e49f51e82d60c4b831c6641314ccf7f4963a5d6bb4d82e
- name: 1.35.0-beta.1/linux/arm64/kops
  sha256: d16d6496c499fecd1245f3c15f51eb92aaae2f8f9c5db6328f744d86b64e7afa
- name: 1.35.0-beta.1/linux/arm64/kops.sha256
  sha256: 086bc142e48946ae80041d285a6b49573c0bb1c085428e44ac30030838e33c52
- name: 1.35.0-beta.1/linux/arm64/nodeup
  sha256: cb2261d48a9a8918e67c1b2b762ae871feabafe4978c597b6583d37b9a8dc446
- name: 1.35.0-beta.1/linux/arm64/nodeup.sha256
  sha256: dc60e7b6c07529468a1774723c548e7cbe6f06437edeaf569eefac9ffa605dac
- name: 1.35.0-beta.1/linux/arm64/protokube
  sha256: 4102485a91563d8160a2b7ae6401201f8b4eb23d4803c7dae98bcbf1ef0ac932
- name: 1.35.0-beta.1/linux/arm64/protokube.sha256
  sha256: aab0f77ef843424337b695a232e5125500c445043caa3d3c3df46d987a72cc94
- name: 1.35.0-beta.1/windows/amd64/kops.exe
  sha256: 5402029418b278c2d038cbaab73b87fea3c175c7515b73de0e0f11413625ad26
- name: 1.35.0-beta.1/windows/amd64/kops.exe.sha256
  sha256: 37ddfcb6c300c6320b8e094fa77014fc58cf8f4784b2abd53c4e8cedcceb5bae
