# formerly a project-level custom role for any project with GKE clusters,
# not actually sure why this account is necessary but here we are
title: ServiceAccount Lister
description: Can list ServiceAccounts
name: iam.serviceAccountLister
include:
  permissions:
  - iam.serviceAccounts.list

