extraObjects:
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: k8s-infra-prow
    spec:
      provider:
        gcpsm:
          projectID: k8s-infra-prow
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: k8s-infra-prow-build
    spec:
      provider:
        gcpsm:
          projectID: k8s-infra-prow-build
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: kubernetes-public
    spec:
      provider:
        gcpsm:
          projectID: kubernetes-public
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: k8s-infra-prow-build-trusted
    spec:
      provider:
        gcpsm:
          projectID: k8s-infra-prow-build-trusted
  - apiVersion: monitoring.googleapis.com/v1
    kind: PodMonitoring
    metadata:
      labels:
        app.kubernetes.io/name: external-secrets
      name: external-secrets
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: external-secrets
      endpoints:
        - port: metrics
          interval: 30s
