apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "karpenter-nodes"

  amiFamily: Bottlerocket
  detailedMonitoring: true
  associatePublicIPAddress: true

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "prow-build-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "prow-build-cluster"

  userData: |
    # Bootstrap the instance using our bootstrap script embeded in a Docker image
    [settings.bootstrap-containers.bootstrap]
    source = "public.ecr.aws/q4o2z4d8/k8s-prow-bottlerocket:v0.0.2"
    mode = "always"
    essential = true

    [settings.kernel.sysctl]
    "fs.inotify.max_user_watches" = "1048576"
    "fs.inotify.max_user_instances" = "8192"
    "vm.min_free_kbytes" = "540672"

  tags:
    Cluster: prow-build-cluster

