extraObjects:
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: broadcom-451918
    spec:
      provider:
        gcpsm:
          projectID: broadcom-451918
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: k8s-infra-prow-build
    spec:
      provider:
        gcpsm:
          projectID: k8s-infra-prow-build
  - apiVersion: monitoring.googleapis.com/v1
    kind: PodMonitoring
    metadata:
      labels:
        app.kubernetes.io/name: external-secrets
      name: external-secrets
      namespace: default
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: external-secrets
      endpoints:
        - port: metrics
          interval: 30s
