- name: kueue
  dmap:
    "sha256:b7730869b937cf6e412140eec7403b4d32fd28bce5fcb014a349032a0ecdc7e4": ["v0.10.2"]
    "sha256:56acd0d3805fee0ec8f071e0dfa41b926d4e5b6f5cf60436ffa42300f6dc17d5": ["v0.10.1"]
    "sha256:bc238183a94983d85483dcb028f2c6dbffe5dee8d9f2b46988680049eb708df9": ["v0.9.4"]
    "sha256:577b280e31a978a82d82da097c236b8ec4ae8323f1c3bfcc06d25eed45d0d874": ["v0.9.3"]
- name: jobset
  dmap:
    "sha256:e1f25f53ba4312f99bb60b92668d98104c549067d86756d30cbf1cf18f2b47f7": ["v0.8.0"]
