# google group for us-central1-docker.pkg.dev/k8s-staging-images/minikube is k8s-infra-staging-minikube@kubernetes.io
registries:
  - name: us-central1-docker.pkg.dev/k8s-staging-images/minikube
    src: true
  - name: asia-east1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: asia-south1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: asia-northeast1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: asia-northeast2-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: australia-southeast1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-north1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-southwest1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-west1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-west2-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-west3-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-west4-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-west8-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-west9-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: europe-west10-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: southamerica-west1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: us-central1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: us-east1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: us-east4-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: us-east5-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: us-south1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: us-west1-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: us-west2-docker.pkg.dev/k8s-artifacts-prod/images/minikube
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
imagesPath: "../../images/k8s-staging-minikube/images.yaml"
