- name: prometheus-adapter
  dmap:
    "sha256:2f34cb3a04a0fee6034f4d63ce3ee7786c0f762dc9f3bf196c70e894dd92edd1": ["v0.10.0"]
    "sha256:b02af0e88509094a72862f2594c00562cbff32c95754285153fda712b02852ba": ["v0.10.1"]
    "sha256:421ab7e37497f792a927d416a6e4b658a10e7879bd36c96f18d7c741fd0dc963": ["v0.11.0"]
    "sha256:e6a43c83ab1656f5371f27dedbb4d99e3c60922af439f1868c7efa5e066c6633": ["v0.11.1"]
    "sha256:1ee5ec118dc55988794b4132b5518de885e35f71a1dcab9c7ba5f811616f9edd": ["v0.9.0"]
    "sha256:d025d1a109234c28b4a97f5d35d759943124be8885a5bce22a91363025304e9d": ["v0.9.1"]
