apiVersion: v1
data:
  config: |
    resources:
    - names:
      - k8s-boskos-powervs-lon04
      - k8s-boskos-powervs-lon04-01
      - k8s-boskos-powervs-lon04-02
      - k8s-boskos-powervs-lon06
      - k8s-boskos-powervs-sao01
      - k8s-boskos-powervs-syd04
      - k8s-boskos-powervs-syd05
      - k8s-boskos-powervs-tok04
      state: dirty
      type: powervs
kind: ConfigMap
metadata:
  name: resources
