apiVersion: v1
data:
  config: |
    resources:
    - names:
      - k8s-boskos-powervs-eu-de-1-01
      - k8s-boskos-powervs-eu-de-1-02
      - k8s-boskos-powervs-eu-de-2-01
      - k8s-boskos-powervs-eu-de-2-02
      - k8s-boskos-powervs-lon06
      - k8s-boskos-powervs-lon06-01
      - k8s-boskos-powervs-lon06-02
      - k8s-boskos-powervs-syd04
      state: dirty
      type: powervs
kind: ConfigMap
metadata:
  name: resources
