apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-reaper
  labels:
    app: boskos-reaper
spec:
  selector:
    matchLabels:
      app: boskos-reaper
  replicas: 1 # one canonical source of resources
  template:
    metadata:
      labels:
        app: boskos-reaper
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: boskos-reaper
          image: gcr.io/k8s-staging-boskos/reaper:v20251218-e3340a3
          args:
            - --boskos-url=http://boskos.test-pods.svc.cluster.local.
            - --resource-type=powervs
