apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - certificate.yaml
  - dashboards.yaml
  - rules.yaml
  - secrets.yaml

configMapGenerator:
  - name: prow-dashboards
    behavior: merge
    files:
      - dashboards/builds.json
      - dashboards/jobs.json
      - dashboards/organizations.json
      - dashboards/repositories.json
