apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  dataFrom:
  - extract:
      key: grafana-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
