# google group for gcr.io/k8s-staging-kops is k8s-infra-staging-kops@kubernetes.io
registries:
- name: gcr.io/k8s-staging-kops
  src: true
- name: us.gcr.io/k8s-artifacts-prod/kops
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/kops
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/kops
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
