apiVersion: v1
data:
  config: |
    resources:
    - names:
      - k8s-infra-e2e-boskos-001
      - k8s-infra-e2e-boskos-002
      - k8s-infra-e2e-boskos-003
      - k8s-infra-e2e-boskos-004
      - k8s-infra-e2e-boskos-005
      - k8s-infra-e2e-boskos-006
      - k8s-infra-e2e-boskos-007
      - k8s-infra-e2e-boskos-008
      - k8s-infra-e2e-boskos-009
      - k8s-infra-e2e-boskos-010
      - k8s-infra-e2e-boskos-011
      - k8s-infra-e2e-boskos-012
      - k8s-infra-e2e-boskos-013
      - k8s-infra-e2e-boskos-014
      - k8s-infra-e2e-boskos-015
      - k8s-infra-e2e-boskos-016
      - k8s-infra-e2e-boskos-017
      - k8s-infra-e2e-boskos-018
      - k8s-infra-e2e-boskos-019
      - k8s-infra-e2e-boskos-020
      - k8s-infra-e2e-boskos-021
      - k8s-infra-e2e-boskos-022
      - k8s-infra-e2e-boskos-023
      - k8s-infra-e2e-boskos-024
      - k8s-infra-e2e-boskos-025
      - k8s-infra-e2e-boskos-026
      - k8s-infra-e2e-boskos-027
      - k8s-infra-e2e-boskos-028
      - k8s-infra-e2e-boskos-029
      - k8s-infra-e2e-boskos-030
      - k8s-infra-e2e-boskos-031
      - k8s-infra-e2e-boskos-032
      - k8s-infra-e2e-boskos-033
      - k8s-infra-e2e-boskos-034
      - k8s-infra-e2e-boskos-035
      - k8s-infra-e2e-boskos-036
      - k8s-infra-e2e-boskos-037
      - k8s-infra-e2e-boskos-038
      - k8s-infra-e2e-boskos-039
      - k8s-infra-e2e-boskos-040
      - k8s-infra-e2e-boskos-041
      - k8s-infra-e2e-boskos-042
      - k8s-infra-e2e-boskos-043
      - k8s-infra-e2e-boskos-044
      - k8s-infra-e2e-boskos-045
      - k8s-infra-e2e-boskos-046
      - k8s-infra-e2e-boskos-047
      - k8s-infra-e2e-boskos-048
      - k8s-infra-e2e-boskos-049
      - k8s-infra-e2e-boskos-050
      - k8s-infra-e2e-boskos-051
      - k8s-infra-e2e-boskos-052
      - k8s-infra-e2e-boskos-053
      - k8s-infra-e2e-boskos-054
      - k8s-infra-e2e-boskos-055
      - k8s-infra-e2e-boskos-056
      - k8s-infra-e2e-boskos-057
      - k8s-infra-e2e-boskos-058
      - k8s-infra-e2e-boskos-059
      - k8s-infra-e2e-boskos-060
      - k8s-infra-e2e-boskos-061
      - k8s-infra-e2e-boskos-062
      - k8s-infra-e2e-boskos-063
      - k8s-infra-e2e-boskos-064
      - k8s-infra-e2e-boskos-065
      - k8s-infra-e2e-boskos-066
      - k8s-infra-e2e-boskos-067
      - k8s-infra-e2e-boskos-068
      - k8s-infra-e2e-boskos-069
      - k8s-infra-e2e-boskos-070
      - k8s-infra-e2e-boskos-071
      - k8s-infra-e2e-boskos-072
      - k8s-infra-e2e-boskos-073
      - k8s-infra-e2e-boskos-074
      - k8s-infra-e2e-boskos-075
      - k8s-infra-e2e-boskos-076
      - k8s-infra-e2e-boskos-077
      - k8s-infra-e2e-boskos-078
      - k8s-infra-e2e-boskos-079
      - k8s-infra-e2e-boskos-080
      - k8s-infra-e2e-boskos-081
      - k8s-infra-e2e-boskos-082
      - k8s-infra-e2e-boskos-083
      - k8s-infra-e2e-boskos-084
      - k8s-infra-e2e-boskos-085
      - k8s-infra-e2e-boskos-086
      - k8s-infra-e2e-boskos-087
      - k8s-infra-e2e-boskos-088
      - k8s-infra-e2e-boskos-089
      - k8s-infra-e2e-boskos-090
      - k8s-infra-e2e-boskos-091
      - k8s-infra-e2e-boskos-092
      - k8s-infra-e2e-boskos-093
      - k8s-infra-e2e-boskos-094
      - k8s-infra-e2e-boskos-095
      - k8s-infra-e2e-boskos-096
      - k8s-infra-e2e-boskos-097
      - k8s-infra-e2e-boskos-098
      - k8s-infra-e2e-boskos-099
      - k8s-infra-e2e-boskos-100
      - k8s-infra-e2e-boskos-101
      - k8s-infra-e2e-boskos-102
      - k8s-infra-e2e-boskos-103
      - k8s-infra-e2e-boskos-104
      - k8s-infra-e2e-boskos-105
      - k8s-infra-e2e-boskos-106
      - k8s-infra-e2e-boskos-107
      - k8s-infra-e2e-boskos-108
      - k8s-infra-e2e-boskos-109
      - k8s-infra-e2e-boskos-110
      - k8s-infra-e2e-boskos-111
      - k8s-infra-e2e-boskos-112
      - k8s-infra-e2e-boskos-113
      - k8s-infra-e2e-boskos-114
      - k8s-infra-e2e-boskos-115
      - k8s-infra-e2e-boskos-116
      - k8s-infra-e2e-boskos-117
      - k8s-infra-e2e-boskos-118
      - k8s-infra-e2e-boskos-119
      - k8s-infra-e2e-boskos-120
      state: dirty
      type: gce-project
    - names:
      - k8s-infra-e2e-boskos-gpu-01
      - k8s-infra-e2e-boskos-gpu-02
      - k8s-infra-e2e-boskos-gpu-03
      - k8s-infra-e2e-boskos-gpu-04
      - k8s-infra-e2e-boskos-gpu-05
      - k8s-infra-e2e-boskos-gpu-06
      - k8s-infra-e2e-boskos-gpu-07
      - k8s-infra-e2e-boskos-gpu-08
      - k8s-infra-e2e-boskos-gpu-09
      - k8s-infra-e2e-boskos-gpu-10
      state: dirty
      type: gpu-project
    - names:
      - k8s-infra-e2e-boskos-scale-01
      - k8s-infra-e2e-boskos-scale-02
      - k8s-infra-e2e-boskos-scale-03
      - k8s-infra-e2e-boskos-scale-04
      - k8s-infra-e2e-boskos-scale-05
      - k8s-infra-e2e-boskos-scale-06
      - k8s-infra-e2e-boskos-scale-07
      - k8s-infra-e2e-boskos-scale-08
      - k8s-infra-e2e-boskos-scale-09
      - k8s-infra-e2e-boskos-scale-10
      - k8s-infra-e2e-boskos-scale-11
      - k8s-infra-e2e-boskos-scale-12
      - k8s-infra-e2e-boskos-scale-13
      - k8s-infra-e2e-boskos-scale-14
      - k8s-infra-e2e-boskos-scale-15
      - k8s-infra-e2e-boskos-scale-16
      - k8s-infra-e2e-boskos-scale-17
      - k8s-infra-e2e-boskos-scale-18
      - k8s-infra-e2e-boskos-scale-19
      - k8s-infra-e2e-boskos-scale-20
      - k8s-infra-e2e-boskos-scale-21
      - k8s-infra-e2e-boskos-scale-22
      - k8s-infra-e2e-boskos-scale-23
      - k8s-infra-e2e-boskos-scale-24
      - k8s-infra-e2e-boskos-scale-25
      - k8s-infra-e2e-boskos-scale-26
      - k8s-infra-e2e-boskos-scale-27
      - k8s-infra-e2e-boskos-scale-28
      - k8s-infra-e2e-boskos-scale-29
      - k8s-infra-e2e-boskos-scale-30
      state: dirty
      type: scalability-project
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: resources
  namespace: test-pods
