apiVersion: v1
kind: ConfigMap
metadata:
  name: www-golang
data:
  # Adding new entries here will make them appear as files in the deployment.
  contrib.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/contrib git https://github.com/kubernetes/contrib">
      <meta name="go-source" content="k8s.io/contrib     https://github.com/kubernetes/contrib https://github.com/kubernetes/contrib/tree/master{/dir} https://github.com/kubernetes/contrib/blob/master{/dir}/{file}#L{line}">
    </head></html>
  examples.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/examples git https://github.com/kubernetes/examples">
      <meta name="go-source" content="k8s.io/examples     https://github.com/kubernetes/examples https://github.com/kubernetes/examples/tree/master{/dir} https://github.com/kubernetes/examples/blob/master{/dir}/{file}#L{line}">
    </head></html>
  gengo.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/gengo git https://github.com/kubernetes/gengo">
      <meta name="go-source" content="k8s.io/gengo     https://github.com/kubernetes/gengo https://github.com/kubernetes/gengo/tree/master{/dir} https://github.com/kubernetes/gengo/blob/master{/dir}/{file}#L{line}">
    </head></html>
  git-sync.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/git-sync git https://github.com/kubernetes/git-sync">
      <meta name="go-source" content="k8s.io/git-sync     https://github.com/kubernetes/git-sync https://github.com/kubernetes/git-sync/tree/master{/dir} https://github.com/kubernetes/git-sync/blob/master{/dir}/{file}#L{line}">
    </head></html>
  heapster.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/heapster git https://github.com/kubernetes/heapster">
      <meta name="go-source" content="k8s.io/heapster     https://github.com/kubernetes/heapster https://github.com/kubernetes/heapster/tree/master{/dir} https://github.com/kubernetes/heapster/blob/master{/dir}/{file}#L{line}">
    </head></html>
  helm.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/helm git https://github.com/kubernetes/helm">
      <meta name="go-source" content="k8s.io/helm     https://github.com/kubernetes/helm https://github.com/kubernetes/helm/tree/master{/dir} https://github.com/kubernetes/helm/blob/master{/dir}/{file}#L{line}">
    </head></html>
  ingress.html: |
    <!DOCTYPE html>
    <html><head>
      <meta name="go-import" content="k8s.io/ingress git https://github.com/kubernetes/ingress">
      <meta name="go-source" content="k8s.io/ingress     https://github.com/kubernetes/ingress https://github.com/kubernetes/ingress/tree/master{/dir} https://github.com/kubernetes/ingress/blob/master{/dir}/{file}#L{line}">
    </head></html>
  kops.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/kops git https://github.com/kubernetes/kops">
      <meta name="go-source" content="k8s.io/kops     https://github.com/kubernetes/kops https://github.com/kubernetes/kops/tree/master{/dir} https://github.com/kubernetes/kops/blob/master{/dir}/{file}#L{line}">
    </head></html>
  kubedash.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/kubedash git https://github.com/kubernetes/kubedash">
      <meta name="go-source" content="k8s.io/kubedash     https://github.com/kubernetes/kubedash https://github.com/kubernetes/kubedash/tree/master{/dir} https://github.com/kubernetes/kubedash/blob/master{/dir}/{file}#L{line}">
    </head></html>
  kube-deploy.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/kube-deploy git https://github.com/kubernetes/kube-deploy">
      <meta name="go-source" content="k8s.io/kube-deploy     https://github.com/kubernetes/kube-deploy https://github.com/kubernetes/kube-deploy/tree/master{/dir} https://github.com/kubernetes/kube-deploy/blob/master{/dir}/{file}#L{line}">
    </head></html>
  kubernetes.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/kubernetes git https://github.com/kubernetes/kubernetes">
      <meta name="go-source" content="k8s.io/kubernetes     https://github.com/kubernetes/kubernetes https://github.com/kubernetes/kubernetes/tree/master{/dir} https://github.com/kubernetes/kubernetes/blob/master{/dir}/{file}#L{line}">
    </head></html>
  kube-ui.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/kube-ui git https://github.com/kubernetes/kube-ui">
      <meta name="go-source" content="k8s.io/kube-ui     https://github.com/kubernetes/kube-ui https://github.com/kubernetes/kube-ui/tree/master{/dir} https://github.com/kubernetes/kube-ui/blob/master{/dir}/{file}#L{line}">
    </head></html>
  minikube.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/minikube git https://github.com/kubernetes/minikube">
      <meta name="go-source" content="k8s.io/minikube     https://github.com/kubernetes/minikube https://github.com/kubernetes/minikube/tree/master{/dir} https://github.com/kubernetes/minikube/blob/master{/dir}/{file}#L{line}">
    </head></html>
  client-go.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/client-go git https://github.com/kubernetes/client-go">
      <meta name="go-source" content="k8s.io/client-go     https://github.com/kubernetes/client-go https://github.com/kubernetes/client-go/tree/master{/dir} https://github.com/kubernetes/client-go/blob/master{/dir}/{file}#L{line}">
    </head></html>
  api.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/api git https://github.com/kubernetes/api">
      <meta name="go-source" content="k8s.io/api     https://github.com/kubernetes/api https://github.com/kubernetes/api/tree/master{/dir} https://github.com/kubernetes/api/blob/master{/dir}/{file}#L{line}">
    </head></html>
  apimachinery.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/apimachinery git https://github.com/kubernetes/apimachinery">
      <meta name="go-source" content="k8s.io/apimachinery     https://github.com/kubernetes/apimachinery https://github.com/kubernetes/apimachinery/tree/master{/dir} https://github.com/kubernetes/apimachinery/blob/master{/dir}/{file}#L{line}">
    </head></html>
  apiserver.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/apiserver git https://github.com/kubernetes/apiserver">
      <meta name="go-source" content="k8s.io/apiserver     https://github.com/kubernetes/apiserver https://github.com/kubernetes/apiserver/tree/master{/dir} https://github.com/kubernetes/apiserver/blob/master{/dir}/{file}#L{line}">
    </head></html>
  apiextensions-apiserver.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/apiextensions-apiserver git https://github.com/kubernetes/apiextensions-apiserver">
      <meta name="go-source" content="k8s.io/apiextensions-apiserver     https://github.com/kubernetes/apiextensions-apiserver https://github.com/kubernetes/apiextensions-apiserver/tree/master{/dir} https://github.com/kubernetes/apiextensions-apiserver/blob/master{/dir}/{file}#L{line}">
    </head></html>
  kube-aggregator.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/kube-aggregator git https://github.com/kubernetes/kube-aggregator">
      <meta name="go-source" content="k8s.io/kube-aggregator     https://github.com/kubernetes/kube-aggregator https://github.com/kubernetes/kube-aggregator/tree/master{/dir} https://github.com/kubernetes/kube-aggregator/blob/master{/dir}/{file}#L{line}">
    </head></html>
  sample-apiserver.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/sample-apiserver git https://github.com/kubernetes/sample-apiserver">
      <meta name="go-source" content="k8s.io/sample-apiserver     https://github.com/kubernetes/sample-apiserver https://github.com/kubernetes/sample-apiserver/tree/master{/dir} https://github.com/kubernetes/sample-apiserver/blob/master{/dir}/{file}#L{line}">
    </head></html>
  test-infra.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/test-infra git https://github.com/kubernetes/test-infra">
      <meta name="go-source" content="k8s.io/test-infra     https://github.com/kubernetes/test-infra https://github.com/kubernetes/test-infra/tree/master{/dir} https://github.com/kubernetes/test-infra/blob/master{/dir}/{file}#L{line}">
    </head></html>
  metrics.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/metrics git https://github.com/kubernetes/metrics">
      <meta name="go-source" content="k8s.io/metrics     https://github.com/kubernetes/metrics https://github.com/kubernetes/metrics/tree/master{/dir} https://github.com/kubernetes/metrics/blob/master{/dir}/{file}#L{line}">
    </head></html>
  autoscaler.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/autoscaler git https://github.com/kubernetes/autoscaler">
      <meta name="go-source" content="k8s.io/autoscaler     https://github.com/kubernetes/autoscaler https://github.com/kubernetes/autoscaler/tree/master{/dir} https://github.com/kubernetes/autoscaler/blob/master{/dir}/{file}#L{line}">
    </head></html>
  utils.html: |
    <html><head>
      <meta name="go-import" content="k8s.io/utils git https://github.com/kubernetes/utils">
      <meta name="go-source" content="k8s.io/utils     https://github.com/kubernetes/utils https://github.com/kubernetes/utils/tree/master{/dir} https://github.com/kubernetes/utils/blob/master{/dir}/{file}#L{line}">
    </head></html>
