apiVersion: v1
kind: Service
metadata:
  name: k8s-io
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: k8s-io
  type: NodePort
  ports:
  - name: http
    port: 80
