apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gcsweb
  labels:
    app: gcsweb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gcsweb-k8s-io
spec:
  tls:
  - secretName: gcsweb-k8s-io-tls
  backend:
    serviceName: gcsweb
    servicePort: http
