# google group for gcr.io/k8s-staging-sig-storage is k8s-infra-staging-sig-storage@kubernetes.io
registries:
- name: gcr.io/k8s-staging-sig-storage
  src: true
- name: us.gcr.io/k8s-artifacts-prod/storage
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/storage
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/storage
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
