apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-pods

resources:
  - boskos-janitor.yaml
  - boskos-reaper.yaml
  - boskos-resources-configmap.yaml
  - boskos.yaml
  - build-serviceaccounts.yaml
  - secrets.yaml
  - limit-range.yaml
  - monitoring.yaml
  - test-pods-poddisruptionbudget.yaml
