apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-account
spec:
  data:
  - remoteRef:
      key: prow-build-service-account
    secretKey: service-account.json
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ssh-key-secret
spec:
  data:
  - remoteRef:
      key: prow-build-ssh-key-secret-ssh-public
    secretKey: ssh-public
  - remoteRef:
      key: prow-build-ssh-key-secret-ssh-private
    secretKey: ssh-private
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials-768319786644
spec:
  data:
  - remoteRef:
      key: gke_k8s-prow-builds_us-central1-f_prow__test-pods__aws-credentials-768319786644
      property: credentials
    secretKey: credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-ssh-key-secret
spec:
  data:
  - remoteRef:
      key: gke_k8s-prow-builds_us-central1-f_prow__test-pods__aws-ssh-key-secret
      property: aws-ssh-private
    secretKey: aws-ssh-private
  - remoteRef:
      key: gke_k8s-prow-builds_us-central1-f_prow__test-pods__aws-ssh-key-secret
      property: aws-ssh-public
    secretKey: aws-ssh-public
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-cip-test-prod-service-account
spec:
  data:
  - remoteRef:
      key: k8s-cip-test-prod-service-account
    secretKey: service-account.json
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-gcr-audit-test-prod-service-account
spec:
  data:
  - remoteRef:
      key: k8s-gcr-audit-test-prod-service-account
    secretKey: service-account.json
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nfd-creds
spec:
  data:
  - remoteRef:
      key: nfd-codecov-token
    secretKey: codecov-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spaces-digitalocean-s3
spec:
  dataFrom:
  - extract:
      key: spaces-digitalocean-s3
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-api-provider-digitalocean-token
spec:
  dataFrom:
  - extract:
      key: cluster-api-provider-digitalocean-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kops-e2e-do-ssh-key
spec:
  dataFrom:
  - extract:
      key: kops-e2e-do-ssh-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-gcp-gcve-credentials
spec:
  data:
    - remoteRef:
        key: k8s-gcp-gcve-ci-password
      secretKey: password
    - remoteRef:
        key: k8s-gcp-gcve-ci-thumbprint
      secretKey: thumbprint
    - remoteRef:
        key: k8s-gcp-gcve-ci-username
      secretKey: username
    - remoteRef:
        key: k8s-gcp-gcve-ci-url
      secretKey: url
  secretStoreRef:
    kind: ClusterSecretStore
    name: broadcom-451918
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scale-pull-cache-token
spec:
  data:
    - remoteRef:
        key: scale-cache-puller-key
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
