apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog

helmCharts:
  - name: datadog
    repo: https://helm.datadoghq.com
    releaseName: datadog
    version: 3.157.0
    kubeVersion: "1.33"
    valuesFile: values.yaml

resources:
  - secrets.yaml
