apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - argocd.yaml This has been manually applied to fix sync issues
  - atlantis.yaml
  - datadog.yaml
  - external-secrets.yaml
  - cert-manager.yaml
  - kyverno.yaml
  - prow.yaml
  - istio.yaml
  - oauth2-proxy.yaml
